#!/usr/bin/env python3
"""Portfolio view across all ventures: current gate, status, gate map, and budget.
Prints a table and (re)writes ventures/INDEX.md.

Run: python automation/portfolio.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VENT = ROOT / "ventures"
GATE_ORDER = ["G0", "G1", "G2", "G3", "G4", "G5", "G6"]
SYMBOL = {"green": "+", "approved": "+", "red": "x", "blocked": "!", "pending": ".", "-": "-"}


def load(p: Path):
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return None


def gate_map(vdir: Path) -> str:
    gd = vdir / "gates"
    out = []
    for g in GATE_ORDER:
        files = list(gd.glob(f"{g}-*.json")) if gd.is_dir() else []
        st = (load(files[0]) or {}).get("status", "?") if files else "-"
        out.append(SYMBOL.get(st, "?"))
    return "".join(out)


def rows():
    if not VENT.is_dir():
        return []
    r = []
    for d in sorted(VENT.iterdir()):
        if not d.is_dir() or d.name.startswith("_"):
            continue
        m = load(d / "manifest.json") or {}
        b = m.get("budget", {}) or {}
        r.append({
            "slug": d.name,
            "title": m.get("title", ""),
            "gate": m.get("current_gate", "?"),
            "status": m.get("status", "?"),
            "gates": gate_map(d),
            "tokens": f"{b.get('tokens_spent', 0)}/{b.get('token_budget_total', '-')}",
            "usd": f"{b.get('api_spend_usd', 0)}/{b.get('api_spend_cap_usd', '-')}",
        })
    return r


def main() -> int:
    r = rows()
    print(f"venture-factory portfolio ({len(r)} venture(s))  "
          f"gates G0-G6: +=green/approved .=pending x=red !=blocked")
    print(f"  {'slug':24} {'gate':5} {'status':14} {'G0-G6':8} {'tokens':16} {'usd':10}")
    for x in r:
        print(f"  {x['slug']:24} {x['gate']:5} {x['status']:14} {x['gates']:8} "
              f"{x['tokens']:16} {x['usd']:10}")

    lines = [
        "# Venture portfolio", "",
        "_Generated by `python automation/portfolio.py`. Gate map G0-G6: "
        "`+` green/approved · `.` pending · `x` red · `!` blocked._", "",
        "| Venture | Title | Gate | Status | G0-G6 | Tokens | USD |",
        "|---|---|---|---|---|---|---|",
    ]
    for x in r:
        lines.append(f"| {x['slug']} | {x['title']} | {x['gate']} | {x['status']} | "
                     f"`{x['gates']}` | {x['tokens']} | {x['usd']} |")
    (VENT / "INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nwrote {(VENT / 'INDEX.md').relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
